name: GitHub Workflows Integration
on: [push, pull_request]

defaults:
  run:
    shell: bash

jobs:
  integration-test:
    name: Integration Test
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        virtenv: [ubuntu-18.04, ubuntu-20.04]
    runs-on: ${{ matrix.virtenv }}
    steps:
      - uses: actions/checkout@v2
      
      - name: Install and Demo
        run: bash demo.sh
